In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import pandas as pd

In [2]:
twoDimensionList = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
twoDimensionListAsTensor = torch.tensor(twoDimensionList)
print(twoDimensionListAsTensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
twoDimensionListAsTensor.ndimension()

2

In [7]:
twoDimensionListAsTensor.size()

torch.Size([3, 3])

In [9]:
numpyTensor = twoDimensionListAsTensor.numpy()

In [10]:
twoDimensionListAsTensor = torch.from_numpy(numpyTensor)

In [21]:
df = pd.DataFrame({'a': [1,2], 'b':[3, 4], 'c':[5, 6]})
tensorFromDf = torch.from_numpy(df.values)
print(tensorFromDf)

tensor([[1, 3, 5],
        [2, 4, 6]])


In [24]:
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
dfTensor = torch.tensor(df.values)
print(dfTensor)

tensor([[11,  3],
        [33,  3],
        [22,  2]])


In [35]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
slicingExample = tensor_example[0:2]
print(slicingExample[1])

tensor([21, 22, 23])


In [50]:
tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(tensor_ques)

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [53]:
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 1st-row first two columns? ", tensor_example[0, 0:2])

What is the value on 1st-row first two columns?  tensor([11, 12])


In [57]:
tensorX = torch.tensor([[1, 2, 3], [1, 3, 5]])
tensorY = torch.tensor([[1, 2], [1, 4], [4, 5]])
tensorNew = torch.mm(tensorX, tensorY)
print(tensorNew)

tensor([[15, 25],
        [24, 39]])
