In [47]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)
from torchvision import transforms

In [48]:
class Toybox(Dataset):
    def __init__(self, length = 100, transform = None):
        self.len = length
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    def __len__(self):
        return self.len

In [49]:
newDataset = Toybox()
newDataset[0]
print(newDataset.len)

100


In [50]:
for i in range(3):
    x, y = newDataset[i]
    print("index", i, "x:", x, "y:", y)

index 0 x: tensor([2., 2.]) y: tensor([1.])
index 1 x: tensor([2., 2.]) y: tensor([1.])
index 2 x: tensor([2., 2.]) y: tensor([1.])


In [51]:
sampleDataset=Toybox(length=50)
print(sampleDataset.len)

50


In [52]:
class addMult(object):
    def __init__(self, addx = 1, muly = 2):
        self.addx = addx
        self.muly = muly

    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x += self.addx
        y *= self.muly
        sample = x,y
        return sample

In [53]:
transform = addMult()
dataset = Toybox(transform = transform)

In [54]:
for i in range(10):
    x, y = dataset[i]
    print(x, y)
    x_, y_ = transform(dataset[i])
    print(x_, y_)

tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])
tensor([3., 3.]) tensor([2.])
tensor([5., 5.]) tensor([8.])


In [55]:
class newMultFunction (object):
    def __init__(self, addX = 5, mulY = 2):
        self.addX = addX
        self.mulY = mulY

    def __call__(self, sample):
        x, y = sample[0], sample[1]
        x += self.addX
        y *= self.mulY
        sample = x, y
        return sample

mf = newMultFunction()
newToySet = Toybox(transform = mf)
for i in range(10):
    print(newToySet[i])

(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))
(tensor([7., 7.]), tensor([2.]))


In [56]:
class mult(object):
    def __init__(self, mult = 100):
        self.mult = mult
    def __call__(self, sample):
        x, y = sample[0], sample[1]
        x *= self.mult
        y *= self.mult
        sample = x, y
        return sample