In [33]:
import torch
from torch.nn import Linear
from torch import nn
torch.manual_seed(1)

In [34]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

def forward(x):
    yhat = b + w*x
    return yhat

x = torch.tensor([[1.0]])
print("The prediction: ", forward(x))

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [35]:
x = torch.tensor([[1.0], [2.0]])
print(x.shape)
forward(x)

torch.Size([2, 1])


tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

In [36]:
x = torch.tensor([[1.0], [2.0], [3.0]])
forward(x)

tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)

In [37]:
lr = Linear(in_features=1, out_features=1, bias=True)
print("Parameters of the function", list(lr.parameters()))

Parameters of the function [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [38]:
print("Dictionary of parameters: ", lr.state_dict())
print("Keys", lr.state_dict().keys())
print("Values", lr.state_dict().values())

Dictionary of parameters:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
Keys odict_keys(['weight', 'bias'])
Values odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [39]:
#Get weight and bias directly
print(lr.weight)
print(lr.bias)

Parameter containing:
tensor([[0.5153]], requires_grad=True)
Parameter containing:
tensor([-0.4414], requires_grad=True)


In [40]:
x = torch.tensor([[1.0],[2.0]])
yhat = lr(x)
print(yhat)

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


In [41]:
x = torch.tensor([[1.0], [2.0], [3.0]])
yhats = lr(x)
print(yhats)

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward0>)


In [42]:
class LinearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out

In [46]:
x = torch.tensor([[1.0],[2.0]])
lrobject = LinearRegression(1,1)
print(lrobject(x))
print("python dict:", lrobject.state_dict())

tensor([[0.3030],
        [0.0973]], grad_fn=<AddmmBackward0>)
python dict: OrderedDict([('linear.weight', tensor([[-0.2057]])), ('linear.bias', tensor([0.5087]))])


In [47]:
lr1 = LinearRegression(1,1)
x = torch.tensor([[1.0], [2.0], [3.0]])
print(lr1(x))

tensor([[0.0166],
        [0.1556],
        [0.2946]], grad_fn=<AddmmBackward0>)
