In [1]:
from torch import nn
import torch
torch.manual_seed(1)

In [2]:
w = torch.tensor([[2.0], [3.0]], requires_grad=True)
b = torch.tensor([[1.0]], requires_grad=True)

In [3]:
def forward(x):
    yhat = torch.mm(x,w) + b
    return yhat

In [4]:
x = torch.tensor([[1.0, 2.0]])
yhat = forward(x)
print("result:", yhat)

result: tensor([[9.]], grad_fn=<AddBackward0>)


In [5]:
X = torch.tensor([[1.0, 1.0], [1.0, 2.0], [1.0, 3.0]])

In [7]:
yhat = forward(X)
print(yhat)

tensor([[ 6.],
        [ 9.],
        [12.]], grad_fn=<AddBackward0>)


In [8]:
model = nn.Linear(2,1)

In [11]:
yhat = model(X)
print(yhat)

tensor([[-0.0848],
        [-0.3969],
        [-0.7090]], grad_fn=<AddmmBackward0>)


In [13]:
class linear_regression(nn.Module):
    def __init__(self, inputsize, outputsize):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(inputsize, outputsize)

    def forward(self,x):
        yhat = self.linear(x)
        return yhat

In [14]:
model = linear_regression(2,1)

In [16]:
print("params",list(model.parameters()))

params [Parameter containing:
tensor([[ 0.3319, -0.6657]], requires_grad=True), Parameter containing:
tensor([0.4241], requires_grad=True)]


In [17]:
yhat = model(x)
print(yhat)

tensor([[-0.5754]], grad_fn=<AddmmBackward0>)


In [18]:
yhat = model(X)

In [19]:
print(yhat)

tensor([[ 0.0903],
        [-0.5754],
        [-1.2411]], grad_fn=<AddmmBackward0>)


In [20]:
lr = linear_regression(2,1)
yhat = lr(X)

In [21]:
print(yhat)

tensor([[0.3126],
        [0.6723],
        [1.0320]], grad_fn=<AddmmBackward0>)
