In [10]:
from torch import nn
import torch

In [11]:
torch.manual_seed(1)

In [12]:
class linearRegression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linearRegression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

In [23]:
model = linearRegression(1,2)
model(torch.Tensor([1.0]))

tensor([ 1.7311, -0.4113], grad_fn=<AddBackward0>)

In [24]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.9812],
         [-0.4231]], requires_grad=True),
 Parameter containing:
 tensor([0.7499, 0.0118], requires_grad=True)]

In [25]:
x = torch.tensor([[1.0]])

In [26]:
yhat = model(x)

In [27]:
yhat

tensor([[ 1.7311, -0.4113]], grad_fn=<AddmmBackward0>)

In [28]:
X = torch.tensor([[1.0], [1.0], [3.0]])

In [29]:
Yhat = model(X)
Yhat

tensor([[ 1.7311, -0.4113],
        [ 1.7311, -0.4113],
        [ 3.6936, -1.2575]], grad_fn=<AddmmBackward0>)