In [10]:
from torch import nn
import torch

In [11]:
torch.manual_seed(1)

In [12]:
class linearRegression(nn.Module):
    def __init__(self,input_size,output_size):
        super(linearRegression,self).__init__()
        self.linear=nn.Linear(input_size,output_size)
    def forward(self,x):
        yhat=self.linear(x)
        return yhat

In [73]:
model = linearRegression(1,3)
model(torch.Tensor([1.0]))

tensor([-0.8394,  0.7502,  0.6327], grad_fn=<AddBackward0>)

In [74]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.6130],
         [ 0.3659],
         [ 0.3095]], requires_grad=True),
 Parameter containing:
 tensor([-0.2264,  0.3843,  0.3232], requires_grad=True)]

In [75]:
x = torch.tensor([[1.0]])

In [76]:
yhat = model(x)

In [77]:
yhat

tensor([[-0.8394,  0.7502,  0.6327]], grad_fn=<AddmmBackward0>)

In [78]:
X = torch.tensor([[1.0], [1.0], [3.0]])

In [79]:
Yhat = model(X)
Yhat

tensor([[-0.8394,  0.7502,  0.6327],
        [-0.8394,  0.7502,  0.6327],
        [-2.0653,  1.4819,  1.2516]], grad_fn=<AddmmBackward0>)